apiVersion: v1
kind: ConfigMap
metadata:
  name: renovate-config
  namespace: renovate
data:
  config.js: |
    module.exports = {
      platform: 'github',
      repositories: ['HuiGong-dev/homelab'],
      onboarding: false,
      dependencyDashboard: true,
      gitAuthor: 'hui-renovate-bot <mmayswift@gmail.com>',
    };
