apiVersion: v1
kind: Secret
metadata:
    name: renovate-token
    namespace: renovate
type: Opaque
stringData:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:LEVjXXZ188Y8CoKGZdnL1M2QuBIDFaogK+yJstU3TxgiSXblInFzug==,iv:g7asY3oHOfi+KsCWDQLWgpHln/sSed3H3+d6Vd36YnQ=,tag:Qtb0GsyxyrqgQu4s7akvpQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMeUQ1TFBBL0N4blRqTitz
            b0ZjLzAwNnhDN3VGZGpzeFdCY3pWWjVLblNNCnpJMTNUempYMGtsODdROE5mK1Jl
            aHBEeVJTa2duL3BZWkMvL3lieFF1RWcKLS0tIDlrK1AyMncvR0o4TVJMRGZNU1Jt
            alhmS0dqeE1HNEs4Ymc4d0N5dVpKTG8Kx/aJBMso2hro7zLLgjnhhhR4GoSnShR+
            JBXez5qCc3Jb6eajpfKcY/ZfVdRMEguwA05aFxjIP3s9EsjdmG2eiQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1uk09pkyhmhgqceskv8e8s6665530t5vwuhvy5nqxx3ckftf0jp5sm2l79d
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-06T10:57:18Z"
    mac: ENC[AES256_GCM,data:hqXt7Obi/T6eYJrM5KiPRei9PvnJzhstAm0ciLEGlhwJUWSzG/UWHMwYm2u9sbFk/l6TsMDlyiXOEqQYIyo+IIL4Pw/JTKoiW4xQzzIdD0zi7Y8rO/LKIZCfyjFozZa1I8oUCrIvvSJOOGOPPG5r5QLjWZUSChKq4uJitar4J44=,iv:Q1ERlYIVVE13eypcNH3xH7OAEJ+qcc0LUvth/9ZQFM8=,tag:TmDa5HNp7kJ7VBcNFo4qrQ==,type:str]
    version: 3.13.1
