apiVersion: v1
kind: Secret
metadata:
  name: renovate-token
  namespace: renovate
type: Opaque
stringData:
  RENOVATE_TOKEN: ENC[AES256_GCM,data:v+dXoCnIROvDCpKLN1/v0+2Qsw8JWSiAPgG3J9BEankGtUr1oFCW9w==,iv:fc0AHk3K0eRSdZ12uTYdwGkLCve9q/B7iX1U6i2aYNs=,tag:w2EykaYMO1XPS4zQCatGRA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMeUQ1TFBBL0N4blRqTitz
        b0ZjLzAwNnhDN3VGZGpzeFdCY3pWWjVLblNNCnpJMTNUempYMGtsODdROE5mK1Jl
        aHBEeVJTa2duL3BZWkMvL3lieFF1RWcKLS0tIDlrK1AyMncvR0o4TVJMRGZNU1Jt
        alhmS0dqeE1HNEs4Ymc4d0N5dVpKTG8Kx/aJBMso2hro7zLLgjnhhhR4GoSnShR+
        JBXez5qCc3Jb6eajpfKcY/ZfVdRMEguwA05aFxjIP3s9EsjdmG2eiQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1uk09pkyhmhgqceskv8e8s6665530t5vwuhvy5nqxx3ckftf0jp5sm2l79d
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-04T18:23:10Z"
  mac: ENC[AES256_GCM,data:+N7R0KChpzbpJ4tDzNItYJK2MJf6o2ZUPOWh5n49g8ROOV9Jur30AeLsH/z/iL1ICdu7YGtkxEiBIN7nH5CsXdievoCj5RwfGC8tvBXApLGoiANWohYrVHWF0N73fdMj/tgTo5BVNf+0FOsZTlodO9YQ8g6i66zNgKWLpPhh7fw=,iv:th4bUaViDfXrhQuxRg4aJr+i/F9q2OS6BiIifw+wwEU=,tag:Cw4s/yU8mPDiu5G6DzHRSA==,type:str]
  version: 3.13.1
