apiVersion: v1
kind: Secret
metadata:
    name: renovate-token
    namespace: renovate
type: Opaque
stringData:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:qEeWneyp9G4IRjDhYqZTly2UypZ8HpJ+YnJKrm1MNBbos1bv8vbEXQb9CwBRcHopD3UisEqYybg1UNB2V2CjLGMsOxGO15mYLL64jcGyh1J3xBME1q6JcRM430Q+,iv:IWiXPKG9vcZlnoNtvhISmWRYILQCzNhKQ6F7bucHb4M=,tag:/U8Hi2nqnp9mEogOut8x8Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMeUQ1TFBBL0N4blRqTitz
            b0ZjLzAwNnhDN3VGZGpzeFdCY3pWWjVLblNNCnpJMTNUempYMGtsODdROE5mK1Jl
            aHBEeVJTa2duL3BZWkMvL3lieFF1RWcKLS0tIDlrK1AyMncvR0o4TVJMRGZNU1Jt
            alhmS0dqeE1HNEs4Ymc4d0N5dVpKTG8Kx/aJBMso2hro7zLLgjnhhhR4GoSnShR+
            JBXez5qCc3Jb6eajpfKcY/ZfVdRMEguwA05aFxjIP3s9EsjdmG2eiQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1uk09pkyhmhgqceskv8e8s6665530t5vwuhvy5nqxx3ckftf0jp5sm2l79d
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-06T10:23:45Z"
    mac: ENC[AES256_GCM,data:WOvXy4Dium+5WNxuHcP5Mpd3q52FO2nc3ZDulidLMpXznff6SDtMiTGM6dAHJHjDvNVc6gE2QvBvXI+rQkQDzTimLGye9UkS5FjhBM8g5zeRM+XsEFUQLS3B7C/oWLh0HHO+B1dPop0SetImKnHoW44IfWSslSzwEstVyFaPaOI=,iv:i9pQUIh+J3zgghJT3Sv4S5hzHI3bQSkKPZdYQYpICCk=,tag:iXItjVQ9NeyntvO5+Xsb0Q==,type:str]
    version: 3.13.1
