{
 "title": "Homelab Kubernetes CronJob and Job Overview",
 "description": "A simple dashboard to monitor k8s CronJobs and standalone Jobs",
 "tags": [
  "homelab",
  "kubernetes"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_pod_info, namespace)"
    }
   },
   {
    "name": "cronjob",
    "label": "CronJob",
    "query": {
     "query": "label_values(kube_cronjob_info{namespace=~\"$namespace\"},cronjob)"
    }
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "query_result(kube_job_info{namespace=~\"$namespace\"} unless on(namespace,job_name) kube_job_owner{namespace=~\"$namespace\",owner_kind=\"CronJob\"})"
    }
   }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "CronJobs and Jobs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Total number of CronJobs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_cronjob_info{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Standalone Jobs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(kube_job_info{namespace=~\"$namespace\"} unless on(namespace,job_name) kube_job_owner{namespace=~\"$namespace\",owner_kind=\"CronJob\"})"
    }
   ]
  },
  {
   "title": "Number of Suspended CronJobs",
   "type": "stat",
   "description": "Must be equal to Zero",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_cronjob_spec_suspend{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Active jobs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_job_status_active{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Failed jobs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_job_failed{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Succeeded jobs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_job_status_succeeded{namespace=~\"$namespace\"}==1)"
    }
   ]
  },
  {
   "title": "Jobs status",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 2 },
   "targets": [
    {
     "expr": "count(kube_job_failed{namespace=~\"$namespace\"}==1)",
     "legendFormat": "Failed"
    },
    {
     "expr": "count(kube_job_status_succeeded{namespace=~\"$namespace\"}==1)",
     "legendFormat": "Succeeded"
    }
   ]
  },
  { "title": "Cronjob Details : $cronjob", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }, "repeat": "cronjob" },
  {
   "title": "Schedule",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1,(kube_cronjob_info{namespace=~\"$namespace\",cronjob=~\"$cronjob\"}))"
    }
   ]
  },
  {
   "title": "Running",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (owner_name)\n(\n  kube_job_status_active{namespace=~\"$namespace\"} * on (job_name)\n\n  group_left(owner_name)\n\n  (group by (job_name,owner_name) (kube_job_owner{owner_name=~\"$cronjob\"}))\n  \n)",
     "legendFormat": "{{label_cronjob_owner}}"
    }
   ]
  },
  {
   "title": "Maximum Duration",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max by (owner_name)\n(\n  max by(job_name )\n   (\n     kube_job_status_completion_time{namespace=~\"$namespace\"} - on (job_name)\n       kube_job_created{namespace=~\"$namespace\"} \n   ) * on (job_name)\n   \n    group_left(owner_name)\n\n  (group by (job_name,owner_name) (kube_job_owner{owner_name=~\"$cronjob\"}))\n\n)  \n\n"
    }
   ]
  },
  {
   "title": "Average Duration",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg by (owner_name)\n(\n  max by(job_name )\n   (\n     kube_job_status_completion_time{namespace=~\"$namespace\"} - on (job_name)\n       kube_job_created{namespace=~\"$namespace\"} \n   ) * on (job_name)\n   \n    group_left(owner_name)\n\n  (group by (job_name,owner_name) (kube_job_owner{owner_name=~\"$cronjob\"}))\n\n)  \n\n\n\n"
    }
   ]
  },
  {
   "title": "$cronjob status",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 9 },
   "targets": [
    {
     "expr": "sum by (owner_name)\n(\n  kube_job_complete{namespace=~\"$namespace\"} + on (job_name)\n\n  group_left(owner_name)\n\n  (group by (job_name,owner_name) (kube_job_owner{owner_name=~\"$cronjob\"}))\n  \n)",
     "legendFormat": "{{label_cronjob_owner}}"
    },
    {
     "expr": "sum by (owner_name)\n(\n  kube_job_failed{namespace=~\"$namespace\"} + on (job_name)\n\n  group_left(owner_name)\n\n  (group by (job_name,owner_name) (kube_job_owner{owner_name=~\"$cronjob\"}))\n  \n)",
     "legendFormat": "{{label_cronjob_owner}}"
    }
   ]
  },
  {
   "title": "Next Schedule",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_cronjob_next_schedule_time{namespace=~\"$namespace\",cronjob=~\"$cronjob\"} * 1000"
    }
   ]
  },
  {
   "title": "Failed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum \n(\n  kube_job_failed{namespace=~\"$namespace\"} + on (job_name)\n\n  group_left(owner_name)\n\n  (group by (job_name,owner_name) (kube_job_owner{owner_name=~\"$cronjob\"}))\n  \n)",
     "legendFormat": "{{label_cronjob_owner}}"
    }
   ]
  },
  {
   "title": "Minimum Duration",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min (\n  (kube_job_status_completion_time{namespace=~\"$namespace\"}\n  - on (job_name)\n    kube_job_created{namespace=~\"$namespace\"})\n  * on (job_name)\n    group_left(owner_name)\n      (group by (job_name,owner_name) (kube_job_owner{owner_name=~\"$cronjob\"}))\n)\n\n\n\n"
    }
   ]
  },
  {
   "title": "Last Schedule",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_cronjob_status_last_schedule_time{namespace=~\"$namespace\",cronjob=~\"$cronjob\"} * 1000"
    }
   ]
  },
  {
   "title": "Succeeded",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum\n(\n  kube_job_complete{namespace=~\"$namespace\"} + on (job_name)\n\n  group_left(owner_name)\n\n  (group by (job_name,owner_name) (kube_job_owner{owner_name=~\"$cronjob\"}))\n  \n)",
     "legendFormat": "{{label_cronjob_owner}}"
    }
   ]
  },
  { "title": "Job Details : $job", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 }, "repeat": "job" },
  {
   "title": "Created",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_job_created{namespace=~\"$namespace\",job_name=~\"$job\"} * 1000"
    }
   ]
  },
  {
   "title": "Running",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_job_status_active{namespace=~\"$namespace\",job_name=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Failed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_job_failed{namespace=~\"$namespace\",job_name=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Succeeded",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_job_complete{namespace=~\"$namespace\",job_name=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kube_job_status_completion_time{namespace=~\"$namespace\",job_name=~\"$job\"} - on(namespace,job_name) kube_job_created{namespace=~\"$namespace\",job_name=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Completed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_job_status_completion_time{namespace=~\"$namespace\",job_name=~\"$job\"} * 1000"
    }
   ]
  }
 ]
}