apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: monitoring
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:odoALuE=,iv:R0JXvUem2wGYhStmHAL4b0YMizQEo01EJIthnPVBa9k=,tag:U6K/9yqKAT4QLz/mrA3ahw==,type:str]
    admin-password: ENC[AES256_GCM,data:Nric/2k0eHeN69d6XOjKeWdQQtyBmcpiRU+KopGMCp67Arz4ULLRcrNtgQw=,iv:eVV6vMI3Kz86GJJONw1zeXRE+/I38iRdf7+CvXaReUQ=,tag:iNFSawIg0eCwP6HF8W40cw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0TWdGeE9PMmlWdHJOMXlz
            cFVwVmc1NENIU3IySW04Y3ZZVEJOM3kyQ2o0Cm5DWTQydm5uWFdSempMYmQ3Y04y
            eFZQWHRwVnhXY0h2MUhvUHJHeTR3RFEKLS0tIGtoeGVQTFJlMnR3aFEyTzNoN0F2
            MXl5WVlwc0wyWTJTdTNMYzBLemNYUWsK6TNUxgRXxYh6f+RARIdTP0T7hmuGereZ
            RY8O2zk1NYBKav9nGJr2yGVrCGTC0+j8UVnZldW0SYex6JdxpQXjsg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1uk09pkyhmhgqceskv8e8s6665530t5vwuhvy5nqxx3ckftf0jp5sm2l79d
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-06T12:07:05Z"
    mac: ENC[AES256_GCM,data:JcDr7Gd0yqUQNQ5lDB6+YJavfFjfz/MLvxBbjo/MGS+Jv3GsWvk1ThlOYNZi010CJPIs3ETQrukt52zFhyegIqiLYZbWmemYtkDuShN0SGmmoF0FLaylnSB1l2Yh9qWowMGyp+E9IE4XvVsFydMfjdCljYbSmTSgs6+huGm3vk4=,iv:oijtLv4HIrNVy9nvsbpWcff7xvm87rM739IG9xKKhEU=,tag:UY0Lojtj2VTQ+dlgUZCSOQ==,type:str]
    version: 3.13.1
