# k3s-server-upgrade-plan.yaml
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: k3s-server-plan
  namespace: system-upgrade
spec:
  concurrency: 1
  cordon: true
  serviceAccountName: system-upgrade

  nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists

  upgrade:
    image: rancher/k3s-upgrade

  version: v1.35.4+k3s1
  #  channel: https://update.k3s.io/v1-release/channels/stable

  window:
    days:
      - saturday
      - sunday
    startTime: "10:00"
    endTime: "22:00"
    timeZone: "Europe/Berlin"