apiVersion: v1
kind: Secret
metadata:
    name: paperless-db-app
    namespace: paperless
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:1MQ3O4wYwG/N,iv:DAgFYraEpEitYtm4WOtAxCaWPQ6csfL8i2TTWGKZ/YI=,tag:52vTTJP8xJfUAS1sy7f27g==,type:str]
    password: ENC[AES256_GCM,data:nxZKhpwwEyJ8dESpvRjD/Fm+tGSMbKW6c2THUSHy8R5K5N+/z+fKRmU8+5qOj/K4,iv:BJGErIu7lbJQ+VyXxMFIir2tn8/js4nbAYlNcYuPmb8=,tag:EM8EhDtwJyLIw2uYip3+JQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXYTZYK0x3eFBlU1k0c0lU
            MjNpRExpaXBNUXhoVjlQYjlIR0dVZmpuQTNFCitSNTVGUjV2VGtrVXhkREdqdE5z
            aVZRdW5wTzBsWGNvcG9Fcjl5K05WUHMKLS0tIGI4dTNXcjNJUXdGaGFqWmV2T1Fn
            Snh0TGhVWFZEWHk4cE00Qy9SVUF1cGMKrvbv3ft2aMQNWvmIyjjuhiFHy5l4cDBL
            F88E5dhRWvew7mqzbS8Sz3gAIYyCFS4aGQgkVLoYIE8VsAbgqFuh4w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1uk09pkyhmhgqceskv8e8s6665530t5vwuhvy5nqxx3ckftf0jp5sm2l79d
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-28T13:07:41Z"
    mac: ENC[AES256_GCM,data:xAkWqGSp6D6WhDsVFaLpp2L3CW/K9FO+kyDxqFeEdX+t+M/96ZvA9fBertW8KqIMj3PWkWZK6is71SzFWwjXEEr/FFJYHXdJHFT3YARHJ3a4w47SglzB1taeDkTmOjkBQscojeUx5EoxV6M8fnBUtdM7licnU+KXIe/R7a14gpM=,iv:7m68dfZ2qaHzkzp7TCRJu4QSAFjvVjBkcogx0+D2bBY=,tag:lLzXH9R83i7ZRSnrJQbGMA==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: paperless-secret
    namespace: paperless
type: Opaque
stringData:
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:PvUnUYJnrNo9tN9K+H+dUZ2vgyvPZdxfUlxISd7kRMIRTY808lNbIK5BI8up3po6Y2RLxgqM9HNMHEx2FVa6hg==,iv:jzYhLixoVrraZzVnNJbJrJMDbf5mqq2p8YNaegU7xM0=,tag:nmubPX1kwXcGXPJeG+319Q==,type:str]
    PAPERLESS_ADMIN_USER: ENC[AES256_GCM,data:pzp+,iv:asE09Al6b3khco72E09BJL70HqkXE3uDr3EA59GemBc=,tag:jS/s0TXmt6IEN7pbo9KyGA==,type:str]
    PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:ZgWR/V67hgFvSH6loSPvLPnsrlWgZPeJZZ5L2NiH9+N37cykOKrvRcfjdjxe9aor,iv:kZKOXl32cW/eLWHQd1RdTTUd+pkxGBtdd8AVBlEEIys=,tag:FHXc96BMkEQZN+oeyAMsWQ==,type:str]
    PAPERLESS_DBUSER: ENC[AES256_GCM,data:Ap9JrpJdME9L,iv:gi2pQZSt0uxiV9fXyRAYvyok9EYVRW7WEXgOgbq6MgA=,tag:3Q127Zj+UgvVkqu8dbi2uA==,type:str]
    PAPERLESS_DBPASS: ENC[AES256_GCM,data:uQwp9VuqURYxyyZH0pHX4YyzQLbLHkDWi+zhOMi8aOUQp3CbPqGs1e1BlRHtHK8U,iv:pTMPXkzfESLt984v9yZQAWRW20uCnpDrCk2VdWlEZ6o=,tag:0TtogHIFXpJPp06HjsExSQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXYTZYK0x3eFBlU1k0c0lU
            MjNpRExpaXBNUXhoVjlQYjlIR0dVZmpuQTNFCitSNTVGUjV2VGtrVXhkREdqdE5z
            aVZRdW5wTzBsWGNvcG9Fcjl5K05WUHMKLS0tIGI4dTNXcjNJUXdGaGFqWmV2T1Fn
            Snh0TGhVWFZEWHk4cE00Qy9SVUF1cGMKrvbv3ft2aMQNWvmIyjjuhiFHy5l4cDBL
            F88E5dhRWvew7mqzbS8Sz3gAIYyCFS4aGQgkVLoYIE8VsAbgqFuh4w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1uk09pkyhmhgqceskv8e8s6665530t5vwuhvy5nqxx3ckftf0jp5sm2l79d
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-28T13:07:41Z"
    mac: ENC[AES256_GCM,data:xAkWqGSp6D6WhDsVFaLpp2L3CW/K9FO+kyDxqFeEdX+t+M/96ZvA9fBertW8KqIMj3PWkWZK6is71SzFWwjXEEr/FFJYHXdJHFT3YARHJ3a4w47SglzB1taeDkTmOjkBQscojeUx5EoxV6M8fnBUtdM7licnU+KXIe/R7a14gpM=,iv:7m68dfZ2qaHzkzp7TCRJu4QSAFjvVjBkcogx0+D2bBY=,tag:lLzXH9R83i7ZRSnrJQbGMA==,type:str]
    version: 3.13.1
