apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:U3Zm2e6ZwZj3Ryo6bg/GRzR7ZalXyfWfWrGJwOD6YQ58jM2QulG4wQ==,iv:UsVy7B1eudvQb7aRk4H5A8cNgqBUnvh5X172NGPVYrA=,tag:+Vb0gtBCNA0gumlc/PX6KQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJYkI4VlhVeVEraXJrcFl4
            VkRIQ3BwaTlDeWRreC95M2ZXc1J0d25sWUJjClVuUEhZVytWb2dKWnJmeTVWbkJZ
            VitkbUZoczdRaDVtV2VjaW5aV0ZkaVkKLS0tIHlSZXZLdXFMSFJ0aS9IWUNQVVI5
            anFNbytsc25zQTV6TUVxRlBsUGRPZ2cKEUqdOeMOXYmaEjUNUCl23T7egLKViRJW
            1oeoo/1uyFUWfNfprz48Kwsk7a81yr49+ZhET+2KsnhS17shsYLCpQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1uk09pkyhmhgqceskv8e8s6665530t5vwuhvy5nqxx3ckftf0jp5sm2l79d
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-05T12:50:13Z"
    mac: ENC[AES256_GCM,data:lJQFhwfjzYt7afnjOlGpWQJUHP9Lor6dlxlEgWmVjoBsZwyQQbumZRxoE7qWxtT/RZ7dXcl1dqjJqLOzC+LwAR8yFvDAJmu+LqZ9WqPIAHtujn2duajAk/BNAVw8VfyXT0IFMugjeOwug3vf+hE+unw31BJRL28McjtxltT24kk=,iv:c0KJNVJzOxCnPCt+uv7APg8ddyF9fkyB6pd5sAQPllw=,tag:vXKWfMRBq02GHLXq0/BthA==,type:str]
    version: 3.13.1
