{
 "title": "Kubernetes Traefik Ingress NextGen",
 "description": "Traefik Ingress Controller via Prometheus Metrics Dashboard, created based on the Kubernetes Nginx Ingress Prometheus NextGen Dashboard @ https://github.com/DevOps-Nirvana/Grafana-Dashboards/tree/main",
 "tags": [
  "ingress",
  "networking",
  "services",
  "k8s",
  "traefik",
  "homelab",
  "kubernetes"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(traefik_router_requests_total,host)"
    }
   },
   {
    "name": "router",
    "label": "Router",
    "query": {
     "query": "label_values(traefik_router_requests_total{host=~\"$host\"},router)"
    }
   },
   {
    "name": "pod",
    "label": "Traefik Pod",
    "query": {
     "query": "label_values(traefik_config_last_reload_success,pod)"
    }
   },
   { "name": "scrape_interval", "label": "Scrape Interval", "query": "30s" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests Total (period)",
   "type": "stat",
   "description": "This is the total number of requests made in this period (top-right period selected)",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(traefik_router_requests_total{host=~\"$host\", router=~\"$router\", pod=~\"$pod\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Reqs (2m)",
   "type": "stat",
   "description": "The number of HTTP requests made in the last 2 minutes.",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(traefik_router_requests_total{ host=~\"$host\", router=~\"$router\"}[2m]))"
    }
   ]
  },
  {
   "title": "% Success (2m)",
   "type": "stat",
   "description": "Percentage of successful requests in the last 2 minutes.\n\nNOTE: Ignoring 404s in this metric, since a  404 is a normal response for errant requests",
   "gridPos": { "h": 3, "w": 5, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(traefik_router_requests_total{code!~\"[4-5].*\", host=~\"$host\", router=~\"$router\", pod=~\"$pod\"}[2m])) / \nsum(rate(traefik_router_requests_total{code!~\"404\", host=~\"$host\", router=~\"$router\", pod=~\"$pod\"}[2m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP 1/2xx (2m)",
   "type": "stat",
   "description": "The number of successful requests in the last 2 minutes.  Successful being 1xx or 2xx by the standard HTTP definition.",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(traefik_router_requests_total{code=~\"(1|2).*\", host=~\"$host\", router=~\"$router\", pod=~\"$pod\"}[2m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP 3xx (2m)",
   "type": "stat",
   "description": "The number of 3xx requests in the 2 minutes.",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(traefik_router_requests_total{code=~\"3.*\", host=~\"$host\", router=~\"$router\", pod=~\"$pod\"}[2m]))"
    }
   ]
  },
  {
   "title": "HTTP 4xx (2m)",
   "type": "stat",
   "description": "This is the number of 4xx requests in the last 2 minutes.",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(traefik_router_requests_total{code=~\"4.*\", host=~\"$host\", router=~\"$router\", pod=~\"$pod\"}[2m]))"
    }
   ]
  },
  {
   "title": "HTTP 5xx (2m)",
   "type": "stat",
   "description": "This is the number of 5xx requests in the last 2 minutes.",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(traefik_router_requests_total{code=~\"5.*\", host=~\"$host\", router=~\"$router\", pod=~\"$pod\"}[2m]))"
    }
   ]
  },
  {
   "title": "Request Volume",
   "type": "timeseries",
   "description": "The request volume of traffic coming to the Traefik pods, measured in requests/second.\n\nThe results shown are aggregated across all selected Traefik routers. However, the graph can also be filtered to display specific routers by using the variables at the top of the dashboard.\n\nFor a more detailed view broken down by router, open the collapsed tab at the bottom. This view is hidden by default because it is CPU-intensive.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(\r\n  rate(\r\n    traefik_router_requests_total{\r\n      host=~\"$host\",\r\n      router=~\"$router\",\r\n      pod=~\"$pod\"\r\n    }[1m]\r\n  )\r\n)",
     "legendFormat": "Volume"
    }
   ]
  },
  {
   "title": "Total HTTP Requests",
   "type": "timeseries",
   "description": "The total number of HTTP requests made within each period.\n\nThe results shown are aggregated across all selected Traefik routers. However, the graph can also be filtered to display specific routers by using the variables at the top of the dashboard.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(sum(increase(traefik_router_requests_total{host=~\"$host\", router=~\"$router\", pod=~\"$pod\"}[1m])))",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Request Sucess Rate",
   "type": "timeseries",
   "description": "The request sucess rate whitin each period.\n\nThe results shown are aggregated across all selected Traefik routers. However, the graph can also be filtered to display specific routers by using the variables at the top of the dashboard.\n\nFor a more detailed view broken down by router, open the collapsed tab at the bottom. This view is hidden by default because it is CPU-intensive.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(traefik_router_requests_total{code!~\"[4-5].*\", host=~\"$host\", router=~\"$router\", pod=~\"$pod\"}[$__rate_interval])) / \r\nsum(rate(traefik_router_requests_total{code!~\"404\", host=~\"$host\", router=~\"$router\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "Rate"
    }
   ]
  },
  {
   "title": "HTTP Status Codes",
   "type": "timeseries",
   "description": "The breakdown of the various HTTP status codes of the requests handled within this period that matches the variables chosen above.\n\nThis chart helps notice and dive into which service is having failures and of what kind.\n\nThe results shown are aggregated across all selected Traefik routers. However, the graph can also be filtered to display specific routers by using the variables at the top of the dashboard.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(sum(increase(traefik_router_requests_total{code=~\"^[1-5][0-9]{2}$\", host=~\"$host\", router=~\"$router\", pod=~\"$pod\"}[1m])) by (code))",
     "legendFormat": "HTTP {{code}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Latency (Percentiles)",
     "type": "timeseries",
     "description": "Ingress latency percentiles, where:\n\nP99 = 99% of requests have a latency equal to or lower than the displayed value.\n\nP90 = 90% of requests have a latency equal to or lower than the displayed value.\n\nP50 = 50% of requests have a latency equal to or lower than the displayed value.\n\nThe results shown are aggregated across all selected Traefik routers. However, the graph can also be filtered to display specific routers by using the variables at the top of the dashboard.\n\nFor a more detailed latency view broken down by router, open the collapsed tab at the bottom. This view is hidden by default because it is CPU-intensive.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(traefik_router_request_duration_seconds_bucket{code!=\"404\",code!~\"[5].*\", router=~\"$router\"}[2m])) by (le))",
       "legendFormat": "P99"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(traefik_router_request_duration_seconds_bucket{code!=\"404\",code!~\"[5].*\", router=~\"$router\"}[2m])) by (le))",
       "legendFormat": "P90"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(traefik_router_request_duration_seconds_bucket{code!=\"404\",code!~\"[5].*\", router=~\"$router\"}[2m])) by (le))",
       "legendFormat": "P50"
      }
     ]
    },
    {
     "title": "Latency Heatmap",
     "type": "heatmap",
     "description": "This graph helps assess and ensure compliance with SLA requirements related to the response time of our services.\n\nThe results shown are aggregated across all selected Traefik routers. However, the graph can also be filtered to display specific routers by using the variables at the top of the dashboard.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "targets": [
      {
       "expr": "round(\n  sum by (le)(\n    increase(\n      traefik_router_request_duration_seconds_bucket{\n        code!=\"404\",code!~\"[5].*\",\n        router =~ \"$router\",\n      }[2m]\n    )\n  )\n)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Open Connections (Controller Pod)",
     "type": "timeseries",
     "description": "NOTE: This does not work per host/route. You can only filter by Traefik pods.\n\nThis is the number of opened connections by Traefik.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 105 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(traefik_open_connections{pod=~\"$pod\"})",
       "legendFormat": "Opened Connections"
      }
     ]
    }
   ]
  },
  {
   "title": "Certificates",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Certificate Expiry",
     "type": "table",
     "description": "Information about expiration dates for certificates used in Ingresses.",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 47 },
     "targets": [
      {
       "expr": "avg(\r\n  traefik_tls_certs_not_after{}\r\n) by (cn) - time()\r\n",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg(\r\n  traefik_tls_certs_not_after{}\r\n) by (cn)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU Intensive / Optional Graphs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Latency per Router (Percentiles)",
     "type": "timeseries",
     "description": "Ingress latency percentiles, where:\n\nP99 = 99% of requests have a latency equal to or lower than the displayed value.\n\nP90 = 90% of requests have a latency equal to or lower than the displayed value.\n\nP50 = 50% of requests have a latency equal to or lower than the displayed value.\n\nThe graph can filtered to display specific routes by using the variables at the top of the dashboard.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(traefik_router_request_duration_seconds_bucket{code!=\"404\",code!~\"[5].*\", router=~\"$router\"}[2m])) by (le, router))",
       "legendFormat": "P99 {{router}}"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(traefik_router_request_duration_seconds_bucket{code!=\"404\",code!~\"[5].*\", router=~\"$router\"}[2m])) by (le, router))",
       "legendFormat": "P50 {{ router}}"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(traefik_router_request_duration_seconds_bucket{code!=\"404\",code!~\"[5].*\", router=~\"$router\"}[2m])) by (le, router))",
       "legendFormat": "P90 {{router}}"
      }
     ]
    },
    {
     "title": "Request Sucess Rate (per Router)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(rate(traefik_router_requests_total{code!~\"[4-5].*\", host=~\"$host\", router=~\"$router\", pod=~\"$pod\"}[$__rate_interval])) by (router) / \r\nsum(rate(traefik_router_requests_total{code!~\"404\", host=~\"$host\", router=~\"$router\", pod=~\"$pod\"}[$__rate_interval])) by (router)",
       "legendFormat": "{{ router }}"
      }
     ]
    },
    {
     "title": "Request Volume",
     "type": "timeseries",
     "description": "The request volume of traffic coming to the Traefik pods, measured in requests/second.\n\nThe results shown are aggregated across all selected Traefik routers. However, the graph can also be filtered to display specific routers by using the variables at the top of the dashboard.\n\nFor a more detailed view broken down by router, open the collapsed tab at the bottom. This view is hidden by default because it is CPU-intensive.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(\r\n  rate(\r\n    traefik_router_requests_total{\r\n      host=~\"$host\",\r\n      router=~\"$router\",\r\n      pod=~\"$pod\"\r\n    }[1m]\r\n  )\r\n) by (router)",
       "legendFormat": "{{router}}"
      }
     ]
    }
   ]
  }
 ]
}