apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: traefik
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:MVTCHah+q32uWSe4KrFgeEJwoVFizNkbrzrcY/PQOS4R8pfA8YgWXw==,iv:mntdF4F7DQJIdtxyGdCtmEY7d7FvqpFT9Mk6YXiects=,tag:+wz/clIFeZMuZR1O7HSP/w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWdHNwZTVQVFhGNkhDMm84
            Y0ZTTUtrUmEwcGFiUnNEWFBIZzlqczVFcmdnCkRNb25SWHZmMitIdmFOaFArWm4r
            eXdOYWJkVzNVRmVLVlVTVFZxMTJYalUKLS0tIFp1UGRjTUM1bnczaDFDQldRZzEv
            V0ZidktVbU1xTWxWb3lKV2hSL01OUkkKfNBqXO3AmpNumLLaEAJ00fbNI46R4jty
            L46NWKpki30H2tn9pARi/C1j30tNBxIZ+gXS0pNhWGbbBOKamU1NUg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1uk09pkyhmhgqceskv8e8s6665530t5vwuhvy5nqxx3ckftf0jp5sm2l79d
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-31T08:48:58Z"
    mac: ENC[AES256_GCM,data:WZaHAlssh26YkA+yYW+Ni88SS1lrc/mCHxipfCG1I3HQ1SpQDTsFEGKDddGsoybpB1aV/vcjEVi/BYWOnn2/CCbWboAJvxko9nh8FFx62eIGEG9caZ0Xfc19GHcL1tqUida+hNkF1XoKCAu4f+rm/sgkENI/yfZKoql0r/kCfA4=,iv:MgdYWVMvlTTkhVp2z+ixf4Yw9kdGkcmFoZnavNwpmxI=,tag:teoA3ulyf9lW5XJmz+eu+w==,type:str]
    version: 3.13.1
