---
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-values
  namespace: flux-system
  labels:
    reconcile.fluxcd.io/watch: Enabled
data:
  values.yaml: |-
    api:
      dashboard: true

    additionalArguments:
      - "--entryPoints.web.http.redirections.entryPoint.to=websecure"
      - "--entryPoints.web.http.redirections.entryPoint.scheme=https"
      - "--entryPoints.web.http.redirections.entryPoint.permanent=true"

    metrics:
      prometheus:
        addRoutersLabels: true
        buckets: "0.005,0.01,0.025,0.05,0.1,0.25,0.5,1.0,2.5,5.0,10.0"
        headerLabels:
          host: X-Forwarded-Host
        service:
          enabled: true
        serviceMonitor:
          enabled: true

    ingressRoute:
      dashboard:
        enabled: true
        annotations:
          external-dns.alpha.kubernetes.io/enabled: "true"
          external-dns.alpha.kubernetes.io/hostname: traefik.home.hgpe.dev
          external-dns.alpha.kubernetes.io/target: 192.168.178.13,192.168.178.14
        entryPoints:
          - websecure
        matchRule: Host(`traefik.home.hgpe.dev`)
        tls: {}
