apiVersion: v1
kind: Secret
metadata:
  name: adguard-configuration
  namespace: external-dns
type: Opaque
stringData:
  url: ENC[AES256_GCM,data:qfUpn/G/RAZhxtij4vB2rr4O7F11,iv:4U59oGxaB2u37VFwn0/XnMxkCVkLYQCyPywkF+KGiIQ=,tag:ItMHww8QfEKLXKTPTH8nog==,type:str]
  user: ENC[AES256_GCM,data:E4D6TAg=,iv:C2cAtp6+nmo8i2ZP0nyWIXxr9afO5k26T3nMhcxhXb4=,tag:L6jwXxioVTUewXvvyz4JUw==,type:str]
  password: ENC[AES256_GCM,data:fkS/koq+kESO8obNeaM=,iv:RP92rvVf+NZApWAmvFlirRZaBmwgZ70zXDJYrpl6aQk=,tag:2VkekkMjfF/CG26yq6WLFg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzSHRkelRWdEI0amZQNGZM
        R0dOWlRZUVJUUXY2RmE2di8wUjFMZ21CaFFNCjVsM0FLelpGNkNwNE4vbW83L0J1
        WEFTOHd0Y2w1VFFNSXpqeitUSWlVR0UKLS0tIHVibEFVc1ZzamJIQkl2T3A0QlI2
        VXR5M2FYeHc5WlZLS3ZuaFJHbWtnRVEK3RVyaFCe6lX6jCfEJ2vbMRrbdq5+jpVW
        Nf3GedyZ1Uue6VriD2LJjdkEKoPIYclw/21SiTpc/gUuowqDxc11nA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1uk09pkyhmhgqceskv8e8s6665530t5vwuhvy5nqxx3ckftf0jp5sm2l79d
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-05T08:37:09Z"
  mac: ENC[AES256_GCM,data:IepcRp97PjRNM6YfklQnUg8AMX/LQ7OvF8gW6RPGc9SyZquvypjst5w62fdcqZaywb8bjQo1OzJzE2Pat00+1TdTYigCGqiM74ssMhqzKfhic3Le/B3K8CIJxszlSXsLmui/s0uxsUuVAXUSgjEAGad5KMEJH8TBwFjOPGhfBFA=,iv:el8LJb+3OqtWm3n9U657bGpAGH29B1bDs8CtAnPMN9k=,tag:Alol6CsfPoqtDvitzEH3GA==,type:str]
  version: 3.13.1
