cloudflare_api_token: ENC[AES256_GCM,data:pu1dcS/armgwy6yMS2Ve+mchzWggtEZdlibr29cVidP4aw5EilnJHQ==,iv:jGoPA7oi0758xSGbLN36mn2XGyYpHOUPa1EX7xLslO0=,tag:bcUdh6IPqm196ClAp9Fi3g==,type:str]
tailscale_auth_key: ENC[AES256_GCM,data:DdlaDxrdqcmj72i48/qoarwq6a0oJkZF/FgM2Qns8x3LF9Ymy0TWiuty2CLKJh8q0Gm8+bv5eNdMai91/VQ=,iv:3lrt3gTmIuGATo6q/BwEUZy4aYMTsUrIIpvu2qIVUDU=,tag:WYBzeBfWbmAE6ipUqJF0DQ==,type:str]
k3s_token: ENC[AES256_GCM,data:CfV+6QnMn8La94lHVzPcc8aCf/oA7ABf4kYvNvZfa9PYGTU1JlhrEi+xTMoGykopwHK3ACbnzLwkXzQsixIcjoYXJrHqbUb+YGwtb+7E7q5WZJ2S9yG+qg0fBaPiPBXpl+x8Zy8tBdsPl38X,iv:egzQIU2GNAAauouJEayesw9hzPo6C7LxgmEHWzmE1a8=,tag:tCJROSUXKBrjXK53vcQ5jA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArNmxDZGpldU90cmkyelp1
            dGYzemtYaVlsRlJHLzAxTDh0eGxLOVg4VWswCjM1UjBSNU02Z0NGUS9ZTE5PdXNT
            WnhvUElERy8yNFNpUVlsR2ZOYlFrL2cKLS0tIHZBV2VuYVpFK0tFSnZJVUdGZXBh
            SHBvdUYwZ2dzUGc1cElYTW1tNVlYa2sKwloIsYz60OlvtL3nanQcX/QqUn3FIJ0f
            dc253vJL/E8pltVWnjP9Jc8KpjeNDCdioXcxk+ZFkJ1qBnaXy0Gb0A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1uk09pkyhmhgqceskv8e8s6665530t5vwuhvy5nqxx3ckftf0jp5sm2l79d
    lastmodified: "2026-05-26T15:03:41Z"
    mac: ENC[AES256_GCM,data:YqUdgwHy1QyhTIF6wnArPrXNbVVvcRYrniVgrOmxy69jKGpIsJZKavBZ3CvkCrFkdp7QU/mf+64WpsMxx/UX24NbZvr+6mwg8dwDkVpELjxP/3YOOuV6MnnmrME4Rs7nC3BDCVlRLSpRgmPwrGkryy7Z3EtXOH4ogQsmJ8aBAAs=,iv:V6E8VWhTQNBgUP44YTGMQ8dt6yIuvgp4lMuPmRp9Ka4=,tag:V29ZH8Z8DyVpUbzDX0/HCw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
