apiVersion: v1
kind: Namespace
metadata:
  name: paperless
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: paperless
type: Opaque
stringData:
  POSTGRES_DB: paperless
  POSTGRES_USER: paperless
  POSTGRES_PASSWORD: change-me
---
apiVersion: v1
kind: Secret
metadata:
  name: paperless-secret
  namespace: paperless
type: Opaque
stringData:
  PAPERLESS_SECRET_KEY: b15a349f6f3c1917122ed32f86a6bd3cae6fbf3b0f1653a697cadd699e3f70cb
  PAPERLESS_ADMIN_USER: hui
  PAPERLESS_ADMIN_PASSWORD: change-me-too
  PAPERLESS_DBUSER: paperless
  PAPERLESS_DBPASS: change-me
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: paperless
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
  namespace: paperless
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-data
  namespace: paperless
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-media
  namespace: paperless
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-consume
  namespace: paperless
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-export
  namespace: paperless
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
