---
- name: Ensure admin users exist
  ansible.builtin.user:
    name: "{{ item.name }}"
    groups: sudo
    append: true
    shell: /bin/bash
    create_home: true
    state: present
  loop: "{{ admin_users }}"

- name: Ensure admin SSH directories exist
  ansible.builtin.file:
    path: "/home/{{ item.name }}/.ssh"
    state: directory
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    mode: "0700"
  loop: "{{ admin_users }}"

- name: Install admin SSH authorized keys
  ansible.posix.authorized_key:
    user: "{{ item.name }}"
    key: "{{ item.ssh_public_key }}"
    state: present
    exclusive: true
  loop: "{{ admin_users }}"

- name: Allow admin users passwordless sudo
  ansible.builtin.copy:
    dest: "/etc/sudoers.d/{{ item.name }}"
    owner: root
    group: root
    mode: "0440"
    content: "{{ item.name }} ALL=(ALL) NOPASSWD:ALL\n"
    validate: /usr/sbin/visudo -cf %s
  loop: "{{ admin_users }}"
