all:
  children:
    homelab_vms:
      hosts:
        adguard:
          ansible_host: 192.168.178.12
          ansible_user: ansible
          ansible_ssh_private_key_file: ~/.ssh/ansible/id_ed25519
          tailscale_hostname: adguard
          tailscale_advertise_routes:
            - 192.168.178.0/24
          tailscale_advertise_exit_node: false
          tailscale_accept_dns: false
          tailscale_accept_routes: false
        k3s-server-01:
          ansible_host: 192.168.178.13
          ansible_user: ansible
          ansible_ssh_private_key_file: ~/.ssh/ansible/id_ed25519  
        k3s-agent-01:
          ansible_host: 192.168.178.14
          ansible_user: ansible
          ansible_ssh_private_key_file: ~/.ssh/ansible/id_ed25519           
    adguard_servers:
      hosts:
        adguard:
    k3s_servers:
      hosts:
        k3s-server-01:    
    k3s_agents:
      hosts:
        k3s-agent-01:        
